### PR TITLE
Account Key Support

### LINKED ISSUE #249: [HVSXROAD] Crossroads of the Elements - Sysop access to all users
**Module Information**
* Identifier [HVSXROAD]
* Module Name [Crossroads of the Elements]
* Version [1.00j]

**Describe the bug**
All users have sysop level access in the game "sys" commands. E.g., SYS GOTO, SYS UPDATE, SYS BECOME, etc...

**To Reproduce**
1. Create new user account
2. Load Crossroads
3. Issue the "sys" command

**Expected behavior**
Only users with "sysop" keys or role should have the ability to run sysop commands.

**Screenshots**
N/A

**Software Information:**
- OS: [Fedora 32 and CentOS 8]
- Telnet Client [Linux telnet, Telix under DOSBox]

### PR DESCRIPTION
**Pull request by enusbaum**
- Adds verification of Account Keys via `haskey()` and `haskeym()`
- Default Keys `DEMO` and `NORMAL` assigned to new users, configurable via `appsettings.json`
- RLOGIN users are given Default Keys
- Database Reset assigns `GUEST` account Default Keys

Fixes #249

### CODE REVIEW

**Review by paladine — CHANGES_REQUESTED** [review]
Tests plz

**Review by paladine — APPROVED** [review]

**Comment by brianmiller** [comment]
Is there a repository of test builds with these changes? I'm happy to test as well. 

I signed up for monthly Patreon support and noticed mentions of test builds, but they looked older than the public releases.

Thanks, again!

**Comment by enusbaum** [comment]
@brianmiller You're able to download the automated builds here: 

https://www.mbbsemu.com/Downloads

They are kicked off any time there's a commit/merge into master. Obviously more experimental than regular releases 😉 

Also thank you for joining the Patreon and directly supporting the project! ❤️

**Comment by brianmiller** [comment]
FWIW, I have #110620-18 running and seems to be working great.  As far as I've tested, only 'sysop' has sysop access in Crossroads, normal users do not, perfect.

Unfortunately, this version of MBBSEmu was crashing every time when just simply replacing the MBBSEmu exec, if I left BBSGEN.DB and BBSUSR.DB in place.  The Crossroads database also had to be deleted.  

I admit I didn't debug this much but we will likely need to ensure a clean upgrade--or at very least a way to backup the user/password database as well as the game databases.

It's looking good!

**Comment by tuday2** [comment]
Apologies yes the change that went in to address that involved some major database schema changes and unfortunately there was no way around it. We are discussing a better way to flag when there is a schema change -- the change to sqlite has been a huge step forward and also having the correct account keys but it also came with having to erase databases. 

Thanks again for testing and feel free to reach out if you have any other issues.

**Pull request merged**
